name: cpscom_admin
description: Modern Group Chat Application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+1.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  linkable: ^3.0.1
  url_launcher: ^6.0.9
  # IOS Icons packages
  cupertino_icons: ^1.0.2

  # Font Awesome Icon Package
  font_awesome_flutter: ^10.1.0

  # Eva Icon Package
  eva_icons_flutter: ^3.1.0

  # Firebase Packages for Authentication
  firebase_auth: ^4.0.1

  # Firebase Packages for Firebase Core Functionalities
  firebase_core: ^2.8.0

  # Firebase Packages for Firestore Database
  cloud_firestore: ^4.1.0

  # Firebase Packages for Storage
  # firebase_storage: ^11.2.0

  # Firebase Packages for Messaging
  firebase_messaging: ^14.6.1

  # Chat Bubble Custom Clipper Package
  flutter_chat_bubble: ^2.0.2

  permission_handler:

  uuid: ^3.0.7

  # Flutter SVG Package for SVG Images
  flutter_svg: ^2.0.5

  # PDF Viewer Package
  syncfusion_flutter_pdfviewer: ^20.3.49
  flutter_pdfview: ^1.3.1
  flutter_cached_pdfview:
  socket_io_client: ^2.0.3+1
  http_parser: ^4.0.2
  open_file: ^3.3.2
  # This Package is for Date and Time
  intl: ^0.18.1
  open_app_file: ^4.0.2
  

  # BLOC Package for State Management
  bloc: ^8.1.1

  # Flutter BLOC Package for State Management
  flutter_bloc: ^8.1.2

  equatable: ^2.0.0
  rxdart: ^0.27.4

  # DIO is for Network Calling Package
  dio: ^5.1.1

  # HTTP Package for API call
  http: ^0.13.4

  # Shared Preference for Store Small Amount of Data Locally
  shared_preferences: ^2.0.11
  get_storage: ^2.1.1
  fluttertoast: ^8.2.4

  # Image Picker is for Pick Gallery Image or Camera Image to Upload
  image_picker: ^0.8.4+11

  # File Picker is for Pick any Type of File (eg. PDF, DOC, TXT, JPG, PNG etc...)
  file_picker: ^5.2.7

  # Cached Network Image is for Network Image Library
  cached_network_image: ^3.3.1

  # Pull Down To Refresh Package
  pull_to_refresh: ^2.0.0
  easy_debounce: ^2.0.3
  shimmer: ^3.0.0

  # zooming feature
  photo_view: ^0.14.0

  # Collection Package for groupBy Function to separate Chats by Date
  collection: ^1.17.0
  overlay_support: ^2.1.0
  

  # Launcher Icons for the Application
  flutter_launcher_icons: ^0.13.1

  # Prevent screenshot & screen recordings
  # flutter_windowmanager: ^0.2.0
  flutter_mentions: ^2.0.1

  # Reply to a particular message
  swipe_to: ^1.0.2
  pdf: ^3.10.4
  focused_menu_custom: ^1.2.0
#   auto complete
  easy_autocomplete: ^1.6.0
  autocomplete_textfield: ^2.0.1
  get:
  #video player
  video_player: ^2.2.17
  chewie: ^1.7.0
  #show the video preview 
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  talker_dio_logger: ^4.3.2
  talker: ^4.3.2


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icons/app-logo.png"
  image_path_ios: "assets/icons/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app-logo.png"
    background_color: "#FFFFFF"
    theme_color: "#5558FF"
  windows:
    generate: true
    image_path: "assets/icons/app-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter Lints Package for Coding Guidelines
  flutter_lints: ^2.0.0

  # Package to Change App Package Name
  change_app_package_name: ^1.1.0

  flutter_local_notifications: ^16.1.0

  firebase_database:

  firebase_core_platform_interface: ^5.0.0


flutter:

  # Material Design Package to Use Material Components
  uses-material-design: true

  # Assets Location for the Application
  assets:
    - assets/images/
    - assets/icons/

  # Fonts Location for the Application
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

